
author:
    - name: Parth Dhorajia
      email: dhorajiap@vcu.edu

date: .4/20/2025

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
